Repository TeamARtique/ARtique-iOS, pull requests merged in 2021-12, with the labels that each got.

#7 ✅[CHORE] : AR SCNLight test
  ARtique/ARtique/Screen/Add/Controller/AddARVC.swift
  ARtique/ARtique/Screen/Home/Storyboard/Detail.storyboard
  ARtique/ARtique/Support/Assets.xcassets/catTest.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/catTest.imageset/catTest.jpg
  ARtique/ARtique/Support/art.scnassets/ship.scn
Labels: 🙋🏻‍♀️ Question, 🚨 도움 필요, ☁️ 윤경, ☁️ 지은, AR🎮

#10 ✨[FEAT] : 바닥인식 기능구현
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Factory/TypeOfViewController.swift
  ARtique/ARtique/Screen/Add/Controller/AddARVC.swift
  ARtique/ARtique/Screen/Add/Storyboard/Base.lproj/Add.storyboard
  ARtique/ARtique/Screen/Plane/Controller/FocusSquare/FocusSquare.swift
  ARtique/ARtique/Screen/Plane/Controller/FocusSquare/FocusSquareSegment.swift
  ARtique/ARtique/Screen/Plane/Controller/PlaneVC.swift
  ARtique/ARtique/Screen/Plane/Controller/Utilities/Utilities.swift
  ARtique/ARtique/Screen/Plane/Storyboard/Plane.storyboard
  ARtique/ARtique/Support/Assets.xcassets/goToExhibitionBtn.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/goToExhibitionBtn.imageset/goToExhibitionBtn.png
  ARtique/ARtique/Support/art.scnassets/ship.scn
Labels: 🍎 Feature, ☁️ 윤경, AR🎮, 🖼 전시뷰

#14 ✅[CHORE] : 홈화면 디자인 수정, Custom navigationBar 추가(임시용)
  ARtique/ARtique/Global/Extension/Notification+Name.swift
  ARtique/ARtique/Screen/Home/Cell/TVC/AllTVC.swift
  ARtique/ARtique/Screen/Home/Cell/TVC/ExhibitionListTVC.swift
  ARtique/ARtique/Screen/Home/Controller/DetailVC.swift
  ARtique/ARtique/Screen/Home/Controller/ExhibitionListVC.swift
  ARtique/ARtique/Screen/Home/Controller/HomeVC.swift
  ARtique/ARtique/Screen/Home/Storyboard/Detail.storyboard
  ARtique/ARtique/Screen/Home/Storyboard/ExhibitionList.storyboard
  ARtique/ARtique/Screen/Home/Storyboard/Home.storyboard
  ARtique/ARtique/Support/Assets.xcassets/Search.imageset/Search.png
  ARtique/ARtique/Support/Assets.xcassets/Ticket.imageset/Ticket.png
  ARtique/ARtique/Support/Assets.xcassets/showAllBtn.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/showAllBtn.imageset/showAllBtn.png
Labels: 📱 View, 🏠 홈탭, ☁️ 윤경

#18 [Feat/#17] link to detail view&ar scene
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Factory/TypeOfViewController.swift
  ARtique/ARtique/Screen/ARGallery/Controller/ARGalleryVC.swift
  ARtique/ARtique/Screen/ARGallery/Storyboard/ARGallery.storyboard
  ARtique/ARtique/Screen/Home/Controller/DetailVC.swift
  ARtique/ARtique/Screen/Home/Storyboard/Detail.storyboard
  ARtique/ARtique/Support/Assets.xcassets/dismissBtn.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/dismissBtn.imageset/dismissBtn.png
  ARtique/ARtique/Support/Assets.xcassets/dismissBtn.imageset/dismissBtn@2x.png
  ARtique/ARtique/Support/Assets.xcassets/dismissBtn.imageset/dismissBtn@3x.png
Labels: 🍎 Feature, 🏠 홈탭, ☁️ 지은
