Repository TeamARtique/ARtique-iOS, pull requests merged in 2022-06, with the labels that each got.

#99 [FEAT] 회원가입 추가 절차 구현
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Enum/AlertType.swift
  ARtique/ARtique/Global/Enum/Vibrate.swift
  ARtique/ARtique/Global/Extension/UIViewController+.swift
  ARtique/ARtique/Global/Extension/UserDefaults+.swift
  ARtique/ARtique/Global/Struct/Identifiers.swift
  ARtique/ARtique/Network/APIModels/Models/Login/LoginDataModel.swift
  ARtique/ARtique/Screen/Login/Controller/LoginVC.swift
  ARtique/ARtique/Screen/Login/Controller/SignupVC.swift
  ARtique/ARtique/Screen/Login/Storyboard/Signup.storyboard
  ARtique/ARtique/Screen/TabBar/Controller/ARtiqueTBC.swift
  ARtique/ARtique/Support/Assets.xcassets/blackLogo.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/blackLogo.imageset/Group 68.png
  ARtique/ARtique/Support/Assets.xcassets/blackLogo.imageset/Group 68@2x.png
  ARtique/ARtique/Support/Assets.xcassets/blackLogo.imageset/Group 68@3x.png
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 📱 View, 🍎 Feature, ☁️ 지은

#103 [FEAT] edit exhibition view
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Enum/AlertType.swift
  ARtique/ARtique/Global/Enum/ToastType.swift
  ARtique/ARtique/Network/APIManagers/ExhibitionDetailAPI.swift
  ARtique/ARtique/Network/APIModels/Models/Detail/DetailModel.swift
  ARtique/ARtique/Network/APIModels/Models/Detail/EditedExhibitionData.swift
  ARtique/ARtique/Network/MoyaTarget/ExhibitionService.swift
  ARtique/ARtique/Screen/Add/Controller/ExhibitionExplainVC.swift
  ARtique/ARtique/Screen/Home/Controller/DetailVC.swift
  ARtique/Pods/Pods.xcodeproj/project.pbxproj
Labels: 📡 Network, 📱 View, 🍎 Feature, ☁️ 윤경

#107 [FEAT] onboarding
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Enum/AlertType.swift
  ARtique/ARtique/Global/Struct/Identifiers.swift
  ARtique/ARtique/Screen/Onboarding/Onboarding.storyboard
  ARtique/ARtique/Screen/Onboarding/OnboardingVC.swift
  ARtique/ARtique/Screen/Splash/SplashVC.swift
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/OnboardingNextBtn.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/OnboardingNextBtn.imageset/OnboardingNextBtn.png
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/OnboardingPrevBtn.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/OnboardingPrevBtn.imageset/OnboardingPrevBtn.png
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/onboarding1.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/onboarding1.imageset/onboarding1.png
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/onboarding2.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/onboarding2.imageset/onboarding2.png
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/onboarding3.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/onboarding3.imageset/onboarding3.png
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/onboarding4.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Onboarding/onboarding4.imageset/onboarding4.png
Labels: 📱 View, 🍎 Feature, ☁️ 윤경

#109 [HOTFIX] 이미지 업로드 기능 구현 & 엑세스토큰 갱신 처리 & 로딩뷰 추가
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ARtique/ARtique/Global/Class/BaseVC.swift
  ARtique/ARtique/Global/Class/LoadingHUD.swift
  ARtique/ARtique/Global/Extension/UIIImage+.swift
  ARtique/ARtique/Network/APIManagers/BaseAPI.swift
  ARtique/ARtique/Network/APIManagers/RegisterAPI.swift
  ARtique/ARtique/Network/APIModels/Models/Add/NewExhibition.swift
  ARtique/ARtique/Network/APIModels/Models/Add/RegisterModel.swift
  ARtique/ARtique/Network/APIModels/Models/Public/ExhibitionModel.swift
  ARtique/ARtique/Network/MoyaTarget/RegisterService.swift
  ARtique/ARtique/Screen/ARGallery/Controller/ARGalleryVC.swift
  ARtique/ARtique/Screen/Add/Controller/AddExhibitionVC.swift
  ARtique/ARtique/Screen/Home/Controller/DetailVC.swift
  ARtique/ARtique/Screen/Home/Controller/HomeListVC.swift
  ARtique/ARtique/Screen/Login/Controller/LoginVC.swift
  ARtique/ARtique/Screen/Login/Controller/SignupVC.swift
  ARtique/ARtique/Screen/Mypage/Controller/ArtistProfileVC.swift
  ARtique/ARtique/Screen/Mypage/Controller/MypageVC.swift
  ARtique/ARtique/Screen/Mypage/Controller/ProfileEditVC.swift
  ARtique/ARtique/Screen/Shared/ExhibitionListVC.swift
  ARtique/ARtique/Screen/Splash/SplashVC.swift
  ARtique/ARtique/Screen/TicketBook/Controller/TicketBookVC.swift
  ARtique/ARtique/Support/AppDelegate.swift
  ARtique/ARtique/Support/Assets.xcassets/loading.dataset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/loading.dataset/loading_converted.gif
  ARtique/ARtique/Support/GoogleService-Info.plist
Labels: 📡 Network, 📱 View, 🍎 Feature, 💡 Refactor, ☁️ 지은, ⚡️ HotFix

#112 [FIX] Firebase sdk -> package를 지우고 pod으로 설치하도록 변경
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique.xcworkspace/xcshareddata/swiftpm/Package.resolved
  ARtique/Podfile
  ARtique/Podfile.lock
  ARtique/Pods/Manifest.lock
  ARtique/Pods/Pods.xcodeproj/project.pbxproj
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/xcschememanagement.plist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.markdown
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.plist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Debug-input-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Debug-output-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Release-input-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Release-output-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks.sh
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique.debug.xcconfig
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique.release.xcconfig
Labels: ☁️ 지은, ⚡️ HotFix

#114 [ADD]: 전시 수정 구현 완료
  ARtique/ARtique/Global/Class/BaseVC.swift
  ARtique/ARtique/Network/APIModels/Models/Detail/EditedExhibitionData.swift
  ARtique/ARtique/Network/MoyaTarget/ExhibitionService.swift
  ARtique/ARtique/Screen/Add/Controller/AddExhibitionVC.swift
  ARtique/ARtique/Screen/Add/Controller/ExhibitionExplainVC.swift
  ARtique/Podfile
  ARtique/Podfile.lock
  ARtique/Pods/Alamofire/LICENSE
  ARtique/Pods/Alamofire/README.md
  ARtique/Pods/Alamofire/Source/Alamofire.swift
  ARtique/Pods/Alamofire/Source/HTTPMethod.swift
  ARtique/Pods/Alamofire/Source/MultipartFormData.swift
  ARtique/Pods/Alamofire/Source/Request.swift
  ARtique/Pods/Alamofire/Source/ServerTrustEvaluation.swift
  ARtique/Pods/Alamofire/Source/Session.swift
  ARtique/Pods/Manifest.lock
  ARtique/Pods/Pods.xcodeproj/project.pbxproj
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/Alamofire.xcscheme
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/Pods-ARtique.xcscheme
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/SnapKit.xcscheme
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/Then.xcscheme
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/xcschememanagement.plist
  ARtique/Pods/Target Support Files/Alamofire/Alamofire-Info.plist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.markdown
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.plist
Labels: 📡 Network, 🍎 Feature, ☁️ 윤경, ✏️ 작성하기탭

#115 [HOTFIX] 티켓북 자잘한 오류/버그들 수정 및 기능 추가
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Class/LoadingHUD.swift
  ARtique/ARtique/Global/Extension/Adjusted+.swift
  ARtique/ARtique/Global/Struct/Identifiers.swift
  ARtique/ARtique/Screen/ARGallery/Controller/ARGalleryVC.swift
  ARtique/ARtique/Screen/ARGallery/Controller/PlaneVC.swift
  ARtique/ARtique/Screen/Home/Controller/HomeVC.swift
  ARtique/ARtique/Screen/Mypage/Controller/MypageVC.swift
  ARtique/ARtique/Screen/TicketBook/Cell/EmptyCVC.swift
  ARtique/ARtique/Screen/TicketBook/Cell/TicketCVC.swift
  ARtique/ARtique/Screen/TicketBook/Cell/TicketHeaderCVC.swift
  ARtique/ARtique/Screen/TicketBook/Controller/TicketBookDimmedVC.swift
  ARtique/ARtique/Screen/TicketBook/Controller/TicketBookVC.swift
  ARtique/ARtique/Screen/TicketBook/Storyboard/TicketBook.storyboard
  ARtique/ARtique/Support/loading.gif
  ARtique/Podfile
  ARtique/Podfile.lock
  ARtique/Pods/Manifest.lock
  ARtique/Pods/Pods.xcodeproj/project.pbxproj
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/xcschememanagement.plist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.markdown
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.plist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Debug-input-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Debug-output-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Release-input-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Release-output-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks.sh
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique.debug.xcconfig
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique.release.xcconfig
Labels: 📱 View, 🍎 Feature, 💡 Refactor, ☁️ 지은, ⚡️ HotFix

#119 [FEAT] AR 기능 추가 (title, 아트워크 상세보기 기능)
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Enum/AlertType.swift
  ARtique/ARtique/Screen/ARGallery/Controller/ARDescVC.swift
  ARtique/ARtique/Screen/ARGallery/Controller/ARGalleryVC.swift
  ARtique/ARtique/Screen/ARGallery/Controller/PresentationController.swift
  ARtique/ARtique/Screen/ARGallery/Storyboard/ARGallery.storyboard
  ARtique/ARtique/Support/Assets.xcassets/ticketAlert.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/ticketAlert.imageset/Frame 69.png
  ARtique/ARtique/Support/Assets.xcassets/ticketAlert.imageset/Frame 69@2x.png
  ARtique/ARtique/Support/Assets.xcassets/ticketAlert.imageset/Frame 69@3x.png
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/xcschememanagement.plist
Labels: 🍎 Feature, ☁️ 지은, ⚡️ HotFix, AR🎮

#118 [FEAT] gallery multi album
  ARtique/ARtique/Screen/Add/Cell/CVC/BorderCVC.swift
  ARtique/ARtique/Screen/Add/Cell/CVC/GalleryCVC.swift
  ARtique/ARtique/Screen/Add/Controller/AddExhibitionVC.swift
  ARtique/ARtique/Screen/Add/Controller/ArtworkSelectVC.swift
  ARtique/Podfile.lock
  ARtique/Pods/Manifest.lock
  ARtique/Pods/Pods.xcodeproj/project.pbxproj
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.plist
Labels: 📱 View, 🍎 Feature, ☁️ 윤경, ✏️ 작성하기탭

#121 [REFACTOR] AR 전시 모델 리펙토링 및 자잘한 수정
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Class/BaseVC.swift
  ARtique/ARtique/Global/Extension/UIViewController+.swift
  ARtique/ARtique/Global/Extension/UserDefaults+.swift
  ARtique/ARtique/Screen/ARGallery/Controller/ARGalleryVC.swift
  ARtique/ARtique/Screen/Add/Controller/AddExhibitionVC.swift
  ARtique/ARtique/Screen/Add/Controller/ExhibitionExplainVC.swift
  ARtique/ARtique/Screen/Home/Controller/DetailVC.swift
  ARtique/ARtique/Screen/Login/Controller/LoginVC.swift
  ARtique/ARtique/Screen/Login/Controller/SignupVC.swift
  ARtique/ARtique/Screen/Mypage/Controller/ArtistProfileVC.swift
  ARtique/ARtique/Screen/Onboarding/OnboardingVC.swift
  ARtique/ARtique/Screen/Shared/Alert.storyboard
  ARtique/ARtique/Screen/Shared/AlertVC.swift
  ARtique/ARtique/Screen/Splash/SplashVC.swift
  ARtique/ARtique/Screen/TicketBook/Controller/TicketBookVC.swift
  ARtique/ARtique/Support/Assets.xcassets/vetaTestIcon.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/vetaTestIcon.imageset/Group 270.png
  ARtique/ARtique/Support/Assets.xcassets/vetaTestIcon.imageset/Group 270@2x.png
  ARtique/ARtique/Support/Assets.xcassets/vetaTestIcon.imageset/Group 270@3x.png
  ARtique/ARtique/art.scnassets/GalleryModel/maximumGallery.scn
  ARtique/ARtique/art.scnassets/GalleryModel/mediumGallery.scn
  ARtique/ARtique/art.scnassets/GalleryModel/minimumGallery.scn
  ARtique/Podfile
  ARtique/Podfile.lock
  ARtique/Pods/Manifest.lock
  ARtique/Pods/Pods.xcodeproj/project.pbxproj
  ARtique/Pods/Pods.xcodeproj/xcuserdata/hwangji.xcuserdatad/xcschemes/xcschememanagement.plist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.markdown
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-acknowledgements.plist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Debug-input-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Debug-output-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Release-input-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks-Release-output-files.xcfilelist
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique-frameworks.sh
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique.debug.xcconfig
  ARtique/Pods/Target Support Files/Pods-ARtique/Pods-ARtique.release.xcconfig
Labels: 🍎 Feature, 💡 Refactor, ☁️ 지은, ⚡️ HotFix, AR🎮

#123 Chore/#122 home paging error
  ARtique/ARtique/Network/APIManagers/MypageAPI.swift
  ARtique/ARtique/Network/APIModels/Models/Mypage/MypageModel.swift
  ARtique/ARtique/Network/MoyaTarget/MypageService.swift
  ARtique/ARtique/Screen/Add/Controller/ThemeVC.swift
  ARtique/ARtique/Screen/Add/Storyboard/ThemeVC.storyboard
  ARtique/ARtique/Screen/Home/Cell/TVC/HomeHorizontalTVC.swift
  ARtique/ARtique/Screen/Home/Controller/HomeListVC.swift
  ARtique/ARtique/Screen/Mypage/Controller/MypageVC.swift
  ARtique/ARtique/Screen/Shared/Alert.storyboard
Labels: 📱 View, 🏠 홈탭, ☁️ 윤경, ⚡️ HotFix

#124 [FEAT] 로그아웃, 회원탈퇴
  ARtique/ARtique.xcodeproj/project.pbxproj
  ARtique/ARtique/Global/Class/BaseVC.swift
  ARtique/ARtique/Global/Enum/AlertType.swift
  ARtique/ARtique/Global/Enum/ToastType.swift
  ARtique/ARtique/Network/APIManagers/MypageAPI.swift
  ARtique/ARtique/Network/MoyaTarget/MypageService.swift
  ARtique/ARtique/Screen/Home/Controller/DetailVC.swift
  ARtique/ARtique/Screen/Mypage/Controller/MypageVC.swift
  ARtique/ARtique/Screen/Mypage/Controller/SettingVC.swift
  ARtique/ARtique/Support/Assets.xcassets/Logout.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Logout.imageset/Logout.png
  ARtique/ARtique/Support/Assets.xcassets/Setting.imageset/Contents.json
  ARtique/ARtique/Support/Assets.xcassets/Setting.imageset/Setting.png
Labels: 📡 Network, 📱 View, 🍎 Feature, ☁️ 윤경, 🤗 마이페이지탭
